---
- hosts: all
  tasks:
    - name: mariadb installation
      apt: name=mariadb-server state=latest
    - name: start mariadb-server
      service:
          name: mariadb
          state: started
